"""empty message

Revision ID: 0f5cdcd191d0
Revises: 5b95b4e7fad5
Create Date: 2018-07-04 10:04:54.866949

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f5cdcd191d0'
down_revision = '5b95b4e7fad5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company', 'Par_value')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company', sa.Column('Par_value', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
