"""empty message

Revision ID: 836d5f48fa9a
Revises: 7ccb8f33c12b
Create Date: 2018-07-03 12:23:26.509912

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '836d5f48fa9a'
down_revision = '7ccb8f33c12b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Company_id', sa.String(length=255), nullable=True),
    sa.Column('Logo', sa.String(length=255), nullable=True),
    sa.Column('Name', sa.String(length=255), nullable=True),
    sa.Column('Details', sa.String(length=255), nullable=True),
    sa.Column('Location', sa.String(length=255), nullable=True),
    sa.Column('Auditors', sa.String(length=255), nullable=True),
    sa.Column('Incorporation_date', sa.String(length=255), nullable=True),
    sa.Column('Listing_Price', sa.String(length=255), nullable=True),
    sa.Column('Shares_Issued', sa.Integer(), nullable=True),
    sa.Column('Financial_Year', sa.String(length=255), nullable=True),
    sa.Column('Par_value', sa.Integer(), nullable=True),
    sa.Column('Parent_Company', sa.String(length=255), nullable=True),
    sa.Column('Address', sa.String(length=255), nullable=True),
    sa.Column('Website', sa.String(length=255), nullable=True),
    sa.Column('Indices', sa.String(length=255), nullable=True),
    sa.Column('Sector', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stocks_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(length=255), nullable=True),
    sa.Column('Company_id', sa.String(length=255), nullable=True),
    sa.Column('Security_id', sa.Integer(), nullable=True),
    sa.Column('High_trade', sa.Integer(), nullable=True),
    sa.Column('Low_trade', sa.Integer(), nullable=True),
    sa.Column('Last_traded_price', sa.Integer(), nullable=True),
    sa.Column('Close_price', sa.Integer(), nullable=True),
    sa.Column('Prev_close', sa.Integer(), nullable=True),
    sa.Column('Vol_traded', sa.Integer(), nullable=True),
    sa.Column('Year_low_price', sa.Integer(), nullable=True),
    sa.Column('Year_high_price', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_stock_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('users', sa.Column('email', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('pass_secure', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('phone_number', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone_number')
    op.drop_column('users', 'pass_secure')
    op.drop_column('users', 'email')
    op.drop_table('user_stock_info')
    op.drop_table('stocks_info')
    op.drop_table('company')
    # ### end Alembic commands ###
