"""empty message

Revision ID: e0b9cf02276e
Revises: 
Create Date: 2018-07-05 20:31:44.917494

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0b9cf02276e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Company_id', sa.String(length=65535), nullable=True),
    sa.Column('Logo', sa.String(length=65535), nullable=True),
    sa.Column('Name', sa.String(length=65535), nullable=True),
    sa.Column('Details', sa.Text(), nullable=True),
    sa.Column('Location', sa.String(length=65535), nullable=True),
    sa.Column('Auditors', sa.String(length=65535), nullable=True),
    sa.Column('Incorporation_date', sa.String(length=65535), nullable=True),
    sa.Column('Listing_Price', sa.String(length=65535), nullable=True),
    sa.Column('Shares_Issued', sa.BigInteger(), nullable=True),
    sa.Column('Financial_Year', sa.String(length=65535), nullable=True),
    sa.Column('Par_value', sa.Float(), nullable=True),
    sa.Column('Parent_Company', sa.String(length=65535), nullable=True),
    sa.Column('Address', sa.String(length=65535), nullable=True),
    sa.Column('Website', sa.String(length=65535), nullable=True),
    sa.Column('Indices', sa.String(length=65535), nullable=True),
    sa.Column('Sector', sa.String(length=65535), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stocks_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Company_id', sa.String(length=65535), nullable=True),
    sa.Column('High_trade', sa.Float(), nullable=True),
    sa.Column('Low_trade', sa.Float(), nullable=True),
    sa.Column('Last_traded_price', sa.Float(), nullable=True),
    sa.Column('Close_price', sa.Float(), nullable=True),
    sa.Column('Prev_close', sa.Float(), nullable=True),
    sa.Column('Vol_traded', sa.BigInteger(), nullable=True),
    sa.Column('Year_low_price', sa.Float(), nullable=True),
    sa.Column('Year_high_price', sa.Float(), nullable=True),
    sa.Column('day', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stockshist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('companyid', sa.BigInteger(), nullable=True),
    sa.Column('json', sa.String(length=255350), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_stock_info',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=65535), nullable=True),
    sa.Column('email', sa.String(length=65535), nullable=True),
    sa.Column('phone_number', sa.BigInteger(), nullable=True),
    sa.Column('pass_secure', sa.String(length=65535), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('user_stock_info')
    op.drop_table('stockshist')
    op.drop_table('stocks_info')
    op.drop_table('company')
    # ### end Alembic commands ###
