"""empty message

Revision ID: e5f19420e3a9
Revises: 8a6a64b5b5c6
Create Date: 2018-07-04 09:57:42.147714

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5f19420e3a9'
down_revision = '8a6a64b5b5c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stocks_info', sa.Column('day', sa.String(length=10), nullable=True))
    op.drop_column('stocks_info', 'Security_id')
    op.drop_column('stocks_info', 'Name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stocks_info', sa.Column('Name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('stocks_info', sa.Column('Security_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('stocks_info', 'day')
    # ### end Alembic commands ###
